services:
  - type: web
    name: voicebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker --timeout 600 main:app
    autodeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: WEAVIATE_URL
        sync: false
      - key: WEAVIATE_API_KEY
        sync: false
    plan: free